name: Package & Publish
on:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: OpenJDK download
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: API installation
      run: mvn -B package install --file api/pom.xml
    - name: TESSERACT package
      run: mvn -B package --file tesseract/pom.xml
      
      
           

